### ISSUE TITLE
no cli __main__.py

### ISSUE THREAD

**Issue by martin0** [asyncee/swagger_codegen#11]
Hi,

I'm following the doc instructions, but running into trouble
I've installed the package with pip
running the suggested command line to generate code complained about no __main__
python -m swagger_codegen generate https://petstore3.swagger.io/api/v3/openapi.json petstore        
C:\...\Python\Python37\python.exe: No module named swagger_codegen.__main__; 'swagger_codegen' is a package and cannot be directly executed

 so i renamed cli\main.py to cli\__main__.py and run this command instead (note swagger_codegen.cli instead of swagger_codegen)
python -m swagger_codegen.cli generate https://petstore3.swagger.io/api/v3/openapi.json petstore    
Generating from https://petstore3.swagger.io/api/v3/openapi.json to . (petstore)

This appears to run successfully
Loaded schema OpenApi30 for Swagger Petstore - OpenAPI 3.0 (1.0.5) with 19 endpoint(s)

**Comment by asyncee** [comment]
Hello, you should run `swagger_codegen` executable, it is available at `<virtualenv dir>/bin/swagger_codegen`.

**Comment by martin0** [comment]
I'm running python 3.7 from visual studio code on windows 10. I'm not using virtualenv.
I don't have a bin folder underneath any python directory in the path
I'm searching my whole drive for swagger_codegen.exe. So far it's found nothing

When I run the command as i describe above for the swagger I really want to use, it fails because my swagger file contains no components element.
It's a 3rd party swagger file, used my many other people, so I presume it is valid.
Do you have any suggestions on modifying swagger_codegen to take this into account?
the swagger url is 
https://interactivebrokers.github.io/cpwebapi/swagger.json

Thanks
Martin

**Comment by martin0** [comment]
I modified loaders.py add_x_names to check for the presence of the components key before looping through schema

The next error i run into is this....
  File "C:\...Python\Python37\lib\site-packages\swagger_codegen\cli\__main__.py", line 35, in generate
    base_schema = load_base_schema(uri)
  File "C:\...Python\Python37\lib\site-packages\swagger_codegen\parsing\loaders.py", line 45, in load_base_schema        
    return loaders.from_dict(schema)
  File "C:\...Python\Python37\lib\site-packages\schemathesis\loaders.py", line 118, in from_dict
    _maybe_validate_schema(raw_schema, spec_schemas.SWAGGER_20, validate_schema)
  File "C:\...Python\Python37\lib\site-packages\schemathesis\loaders.py", line 148, in _maybe_validate_schema
    jsonschema.validate(instance, schema)
  File "C:\...Python\Python37\lib\site-packages\jsonschema\validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: 'Object' is not one of ['array', 'boolean', 'integer', 'null', 'number', 'object', 'string']

Failed validating 'enum' in schema[0]:
    {'enum': ['array',
              'boolean',
              'integer',
              'null',
              'number',
              'object',
              'string']}

Thanks
Martin

**Comment by martin0** [comment]
found swagger_codegen.exe in C:\Users\...\AppData\Local\Programs\Python\Python37\Scripts :-)
However I prefer to continue as i am, considering code changes required

**Comment by asyncee** [comment]
Unfortunately, only openapi 3 is supported (https://swagger.io/specification/), and https://interactivebrokers.github.io/cpwebapi/swagger.json appears to be swagger 2.0.

You can try some tools (like https://mermade.org.uk/openapi-converter) to convert 2 to 3.

**Comment by martin0** [comment]
Thanks for the heads up on that.

**Comment by martin0** [comment]
I've successfully converted to openapi json but got some other issues. I'll submit a separate report
