### ISSUE TITLE
no name 'BaseModel' in module pydantic

### ISSUE THREAD

**Issue by martin0** [asyncee/swagger_codegen#13]
the error in the title is given by this line

from pydantic import BaseModel

I'm using pydantic 1.7.2.
The given error appears to be truthful

Martin

**Comment by martin0** [comment]
Hmm class BaseModel is in main.py of pydantic. Not sure why its not found by vscode ide

**Comment by asyncee** [comment]
True. You can see that pydantic exports `BaseModel`: https://github.com/samuelcolvin/pydantic/blob/master/pydantic/__init__.py#L36
