### ISSUE TITLE
Literal not in typing.py

### ISSUE THREAD

**Issue by martin0** [asyncee/swagger_codegen#17]
Apparently the answer is
https://github.com/python/typing/issues/707
 pip3 install typing_extensions and then use from typing_extensions import Literal.

might be useful to include something about this in the code?

**Comment by coderfromhere** [comment]
3.7 is two major releases behind, it's just worth upgrading to 3.8 or 3.9. The package itself [is published on PyPI](https://pypi.org/project/swagger-codegen/) as 3.8+ compatible
![Screen Shot 2020-12-03 at 15 53 13](https://user-images.githubusercontent.com/59691490/101053611-e4c27500-357f-11eb-9b29-ee7fb86185ab.png)

**Comment by martin0** [comment]
fair point, i hadn't spotted that - thanks
