### ISSUE TITLE
another class None and schema names containing - produce invalid python

### ISSUE THREAD

**Issue by martin0** [asyncee/swagger_codegen#18]
sample below illustrates the issue.
the sample also creates an issue with post__v1_portal_iserver_secdef_search (another class None) - not sure why
perhaps because the type is object, with no definition of object...

'''
{
    "openapi": "3.0.0",
    "info": {
        "title": "Client Portal Web API",
        "description": "Production version of the Client Portal Web API",
        "version": "1.0.0"
    },
    "paths": {
	        "/iserver/secdef/search": {
            "post": {
                "summary": "Search by symbol or name",
                "tags": [
                    "Contract"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": [
                                    "symbol"
                                ],
                                "properties": {
                                    "symbol": {
                                        "type": "string",
                                        "description": "symbol or name to be searched"
                                    },
                                    "name": {
                                        "type": "boolean",
                                        "description": "should be true if the search is to be performed by name. false by default."
                                    },
                                    "secType": {
                                        "type": "string",
                                        "description": "If search is done by name, only the assets provided in this field will be returned. Currently, only STK is supported."
                                    }
                                }
                            }
                        }
                    },
                    "description": "symbol or name to be searched",
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "returns an array of results",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "conid": {
                                                "type": "integer"
                                            },
                                            "companyHeader": {
                                                "type": "string"
                                            },
                                            "companyName": {
                                                "type": "string"
                                            },
                                            "symbol": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            },
                                            "opt": {
                                                "type": "string"
                                            },
                                            "war": {
                                                "type": "string"
                                            },
                                            "sections": {
                                                "type": "array",
                                                "items": {
                                                    "type": "object"
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "error while processing the request",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "error": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },

	        "/iserver/account": {
            "post": {
                "summary": "Updates currently selected account to the provided account",
                "description": "If an user has multiple accounts, and user wants to get orders, trades, etc. of an account other than currently selected account, then user can update the currently selected account using this API and then can fetch required information for the newly updated account.",
                "tags": [
                    "Account"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/set-account"
                            }
                        }
                    },
                    "description": "account id",
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "an object containing updated account ID",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "set": {
                                            "type": "boolean"
                                        },
                                        "acctId": {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

    },
    "servers": [
        {
            "url": "https://localhost:5000/v1/portal"
        }
    ],
    "components": {
        "requestBodies": {
            "Body": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "acctIds": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "description": "account id"
                                    }
                                }
                            }
                        }
                    }
                },
                "description": "an array of account ids",
                "required": true
            }
        },
        "schemas": {
		    "set-account": {
                "type": "object",
                "properties": {
                    "acctId": {
                        "type": "string",
                        "description": "Account ID"
                    }
                }
            },

    
        }
    }
}
'''

**Comment by martin0** [comment]
Any word on when the class None issue illustrated here, may be looked at? Much appreciated

**Comment by asyncee** [comment]
Sorry, i'm completely forgot to notify you that it is fixed in 1.0.27 (0.1.28 is the most recent released version). Unfortunately 0.1.27 does not fix related issue described in #19.

**Comment by martin0** [comment]
I've upgraded to python 3.8 (latest supported by tensorflow atm)
I'm using swagger-codegen       0.1.28 so far as i can tell.
The problem illustrated by the above json still exists. Its a different scenario to the one previously fixed in 0.1.27 i believe

**Comment by martin0** [comment]
i'd be grateful if you could take another look

**Comment by asyncee** [comment]
It looks like #19 describes same issue, lets move discussion there. Thanks! I'll try to look into that asap.

**Comment by martin0** [comment]
Thanks :-) please note, the sample here illustrates 2 issues 
Over to #19

**Comment by asyncee** [comment]
Sure, currently i'm fixing some other bugs in the library and soon will get to that one.

**Comment by asyncee** [comment]
I have implemented a fix that is available in master currently.

Can you check it out if it works for your cases?

**Comment by martin0** [comment]
the supplied json generates without class None
- thanks
- please note another sample supplied in a new issue - sorry
