### ISSUE TITLE
self.make_request() causing an attribute error because it doesn't have the right response codes

### ISSUE THREAD

**Issue by dmo9** [asyncee/swagger_codegen#2]
&nbsp;
### For a particular endpoint, my json contract has the following responses:
&nbsp;
![responses](https://user-images.githubusercontent.com/28460065/87359247-69f7af80-c535-11ea-837d-637fe9e8c904.PNG)

### But the corresponding make_request function, which was created by the generate command, only handles a 200 response code:
&nbsp;
![return](https://user-images.githubusercontent.com/28460065/87359516-f1ddb980-c535-11ea-920e-de20638db9f0.PNG)

### Because of this, I'm getting the following attribute error:

![image](https://user-images.githubusercontent.com/28460065/87359596-1c2f7700-c536-11ea-856a-cc1870708aa5.png)

### Manually including the response codes fixes the issue, but I would assume there's an error in the generate command .

**Comment by asyncee** [comment]
Thank you for bug report. I will look into this as soon as possible, it is definitely a bug. Also currently tests are missing because the project is still in early stage of development.

**Comment by dmo9** [comment]
Awesome! And thank you for all the work you've done on this project, it has saved me tons of time.

**Comment by asyncee** [comment]
Could you share your schema please? I can not reproduce problem using latest version (0.1.13)

**Comment by dmo9** [comment]
[https://developer.ebay.com/api-docs/master/sell/inventory/openapi/3/sell_inventory_v1_oas3.json](Schema)

**Comment by dmo9** [comment]
The operationId for the example I provided above is "createInventoryLocation"

**Comment by asyncee** [comment]
@dmo9 please, check if you are using latest swagger-codegen version. According to traceback `content_types` variable is `None`, but there is a guard in upstream version of code: https://github.com/asyncee/swagger_codegen/blob/master/src/swagger_codegen/api/base.py#L69

**Comment by asyncee** [comment]
Steps to check if issue still exists:

1. Update to latest version (0.1.13), regenerate api client and check if `createInventoryLocation` method is working.
2. Install `swagger-codegen` directrly from master branch, regenerate api client and check if `createInventoryLocation` method is working.

If second option will work for you, i'll release new version.

**Comment by dmo9** [comment]
So I was using 0.1.6 and updating to 0.1.13 did prevent the traceback error but if I'm understanding things correctly, I believe self.make_request is still not being populated correctly.

![image](https://user-images.githubusercontent.com/28460065/87515277-9bfa3600-c649-11ea-9b2d-33ab06d34740.png)

Also, I've noticed that Configuration no longer accepts headers as a key word argument. Is there a different way to include them in the request manually or are they all supposed to be defined in the contract?

**Comment by asyncee** [comment]
First argument to `self.make_request` is of type `ResponseMapping`. ResponseMapping holds known status codes, content types and their responses. In current release (0.1.13), this mapping is filled only with responses that have a schema. That's right — there are no point to fill response mappings if there are no valid response type. If remote api returns something that is not a known response, `swagger-codegen` then interprets it as `None`, so response will be `None`.

I agree that it is not obvious, so i have pushed a change to the master branch that fills response mapping with all declared status codes, so it can be easily understood by reader of the code. This does not change the behaviour of an api client.

Request hook is a callable function that accepts an `ApiRequest` and produces new  `ApiRequest`. With request hooks one can change `ApiRequest` in any ways, not only headers. For example, one of my projects have a hook that provides `Correlation-Id` header, specific for current flask request context.

Example:

```python
from swagger_codegen.api.configuration import Hook

def add_api_key(request: ApiRequest) -> ApiRequest:
    # Mutate request, just as an example.
    request.headers.update({'ApiKey': 'abcd'})
    return request

configuration=Configuration(
    host=host, hooks={Hook.request: [add_api_key]}
),
```

Hooks allow swagger-codegen clients to integrate into any infrastructure.

**Comment by asyncee** [comment]
Could you try master branch and report if everything okay for you?

**Comment by dmo9** [comment]
I'm now using the master branch and everything works perfectly. And thank you, you've helped me improve as a coder

**Comment by asyncee** [comment]
> I'm now using the master branch and everything works perfectly. And thank you, you've helped me improve as a coder

Thats great!

I've pushed 0.1.14 to the pypi so you can use that instead of master branch.
